version: '3'

services:
  calculator:
    image: duclv1132/calculator
    build:
      context: ./calculator
      dockerfile: Doggerfile
    networks:
      [ "abcxyz", "cdeijk" ]
    ports:
      - "9090:9090"

  registration:
    image: duclv1132/registration
    build: ./registration
    networks:
      - abcxyz
    ports:
      - "9092:9092"

  web:
    image: duclv1132/web
    networks:
      - abcxyz
    build: ./web
#    8192 : port app dang ky voi docker
#    8888: port docker xuat ra cho client goi vao
    ports:
      - "8888:8888"
    depends_on:
      - student
      - registration
      - calculator

  student:
    image: duclv1132/student
    networks:
      - abcxyz
    build: ./student
    ports:
      - "8083:8083"

networks:
  abcxyz:
    external: true
  cdeijk:
    external: true

