version: '3'
services:

  calculator-service:
    image: calculator
    build: ./calculator
    ports:
      - "9090:9090"
    networks:
      - my-network

  registration:
    image: registration
    build: ./registration
    ports:
      - "9092:9092"
    networks:
      - my-network

  web-service:
    image: web
    build: ./web
    ports:
      - "8888:8888"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


