version: '3'

services:
  calculator-service:
    image: duclv1132/calculator
    build: ./calculator
    networks:
      - abcxyz
    ports:
      - "9090:9090"

  registration:
    image: duclv1132/registration
    build: ./registration
    networks:
      - abcxyz
    ports:
      - "9092:9092"

  web-service:
    image: duclv1132/web
    networks:
      - abcxyz
    build: ./web
    ports:
      - "8888:8888"

networks:
  abcxyz:
    external: true

