// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caculator.proto

package com.example.autogen.grpc.calculator;

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   */
  int getSum();
}
