// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caculator.proto

package com.example.autogen.grpc.calculator;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 numbers = 1;</code>
   */
  java.util.List<Integer> getNumbersList();
  /**
   * <code>repeated int32 numbers = 1;</code>
   */
  int getNumbersCount();
  /**
   * <code>repeated int32 numbers = 1;</code>
   */
  int getNumbers(int index);
}
