spring:
  config:
    additional-location: classpath:/,classpath:/config/,classpath:/envs/
    name: application
grpc:
  client:
    calculator:
      address: ${CALCULATOR_ADDRESS}:9090
      negotiationType: plaintext
    registration:
      address: ${REGISTRATION_ADDRESS}:9092
      negotiationType: plaintext
server:
  port: 8888