#grpc:
#  client:
#    calculator:
#      address: calculator:9090
#      negotiationType: plaintext
#    registration:
#      address: registration:9092
#      negotiationType: plaintext
server:
  port: 8888