// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package com.example.autogen.grpc.registration;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
