// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: registration.proto

package com.example.autogen.grpc.registration;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:registration.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
